//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaptionMaster
    {
        public int CaptionID { get; set; }
        public string Caption { get; set; }
        public int BrandID { get; set; }
    
        public virtual BrandMaster BrandMaster { get; set; }
    }
}
