//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimateScheduled
    {
        public int EST_SchID { get; set; }
        public int EST_EditionID { get; set; }
        public int EST_PUBID { get; set; }
        public int EST_ID { get; set; }
        public System.DateTime Scheduled_Date { get; set; }
        public int CaptionID { get; set; }
        public string Language { get; set; }
        public decimal Hight { get; set; }
        public decimal Weight { get; set; }
        public decimal Total_Size { get; set; }
        public decimal Rate { get; set; }
        public int NoOfInsertion { get; set; }
        public decimal Total_Cost { get; set; }
        public decimal Agency_Discount { get; set; }
        public decimal Total_NetCost { get; set; }
    }
}
