//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimateHeader
    {
        public EstimateHeader()
        {
            this.EstimateEditions = new HashSet<EstimateEdition>();
            this.EstimatePublications = new HashSet<EstimatePublication>();
        }
    
        public int EST_ID { get; set; }
        public string EST_NO { get; set; }
        public System.DateTime EST_Date { get; set; }
        public string Campaign { get; set; }
        public string Agency { get; set; }
        public string PO_NO { get; set; }
        public System.DateTime PO_Date { get; set; }
        public System.DateTime PeriodForm { get; set; }
        public System.DateTime PeriodTo { get; set; }
        public Nullable<decimal> SAC_PER { get; set; }
        public Nullable<decimal> AAC_PER { get; set; }
        public Nullable<decimal> Gross_Cost { get; set; }
        public Nullable<decimal> Net_Cost { get; set; }
        public int Status { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> BrandID { get; set; }
    
        public virtual ICollection<EstimateEdition> EstimateEditions { get; set; }
        public virtual ICollection<EstimatePublication> EstimatePublications { get; set; }
    }
}
